version: '3.0'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - 'db:db'
      - 'redis:redis'
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    command: redis-server
    volumes:
      - 'redis_data:/data'

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db_data:
  redis_data: